name: fanglinhaidan

on:
  workflow_dispatch:
  schedule:
    - cron: '40 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fanglinhaidan
        env:
          c995: ${{ secrets.c995 }}
        run: |
          echo $c995 | jq -r .mhhlu8 | /bin/bash
          echo $brz00810 | jq -r .eg14869 | /bin/bash
          echo $acl12779 | jq -r .n04074 | /bin/bash

